# Generated by Django 4.0.2 on 2022-02-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=100, verbose_name='Second Name')),
                ('first_surname', models.CharField(max_length=100, verbose_name='First Surname')),
                ('second_surname', models.CharField(max_length=100, verbose_name='Second Surname')),
                ('document_number', models.CharField(max_length=100, verbose_name='Document Number')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.BigIntegerField(verbose_name='Phone')),
                ('date_birth', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'Person',
                'ordering': ['document_number'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Position',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type_Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_document', models.CharField(max_length=100, verbose_name='Type Document')),
            ],
            options={
                'verbose_name': 'Type Document',
                'ordering': ['type_document'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
            options={
                'verbose_name': 'User',
                'ordering': ['id_person'],
            },
        ),
        migrations.CreateModel(
            name='User_Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BinaryField(verbose_name='State')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'User Position',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.type_document'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person')),
            ],
            options={
                'verbose_name': 'Customer',
                'ordering': ['person'],
            },
        ),
    ]
