# Generated by Django 4.0.2 on 2022-02-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('cost_sale', models.IntegerField(verbose_name='Cost Sale')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['name'],
            },
        ),
    ]
