# Generated by Django 4.0.2 on 2022-02-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('reason', models.CharField(max_length=100, verbose_name='Reason')),
                ('remarks', models.TextField(null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Devolution',
                'ordering': ['reason'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('cost_sale', models.IntegerField(verbose_name='Cost Sale')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('reference', models.CharField(max_length=100, verbose_name='Reference')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NIT', models.CharField(max_length=100, verbose_name='NIT')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.BigIntegerField(verbose_name='Phone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('email_address', models.EmailField(max_length=100, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Provider',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.IntegerField(verbose_name='Invoice Number')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Sale',
                'ordering': ['invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('purchase_cost', models.IntegerField(verbose_name='Purchase Cost')),
                ('invoice_number', models.IntegerField(verbose_name='Invoice Number')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.provider')),
            ],
            options={
                'verbose_name': 'Purchase',
                'ordering': ['invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warranty_start', models.DateField(verbose_name='Warranty Start')),
                ('warranty_end', models.DateField(verbose_name='End Warranty')),
                ('remarks', models.TextField(max_length=250, null=True, verbose_name='Remarks')),
                ('serial', models.IntegerField(verbose_name='Serial')),
                ('state', models.BinaryField(verbose_name='State')),
                ('devolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.devolution')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.purchase')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sale')),
            ],
            options={
                'verbose_name': 'Item',
                'ordering': ['serial'],
            },
        ),
    ]
